version: '3.8'

networks:
  art-portfolio-network:

services:
  client:
    build:
      context: ./client
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - art-portfolio-network
  
  server:
    build:
      context: ./server
      args:
        NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
      - PORT=${PORT}
    networks:
      - art-portfolio-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - art-portfolio-network