version: '3.8'

services:
  client:
    build:
      context: ./client
      args:
        NODE_ENV: production
    ports:
      - "80:80"
    networks:
      - app_network
  
  server:
    build:
      context: ./server
      args:
        NODE_ENV: production
    ports:
      - "3001:3001"
    environment:
      - SECRET=${SECRET}
      - STRIPE_SK=${STRIPE_SK}
      - RDS_HOSTNAME=${RDS_HOSTNAME}
      - RDS_PORT=${RDS_PORT}
      - DATABASE_URL=mysql://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge